#!/usr/bin/env ruby

require 'fileutils'
require 'erb'

TEMPLATE     = File.join(File.dirname(__FILE__), 'nchan.conf.erb')
NCHAN_CONFIG = File.join(File.dirname(__FILE__), 'nchan.conf')

erb = ERB.new(File.read(TEMPLATE)).result
File.write(NCHAN_CONFIG, erb)
