#!/bin/bash
# scripts/build_nchan <build_dir> <nginx_dir> <nchan_dir_relative>
# Build NGINX and NCHAN and modules on Heroku

build_dir=$1
nginx_dir=$2
nchan_dir_relative=$3

echo "-----> nchan-buildpack: Building NGINX with NCHAN"

(
    cd ${nginx_dir}
    ./configure \
        --prefix=${build_dir}/bin/nginx \
        --add-module=${nchan_dir_relative}
    make
    make install
)
